[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    lovyan03/LovyanGFX@^1.2.7

[env:esp32dev_usb]
upload_speed = 921600

[env:esp32dev_ota]
upload_protocol = espota
upload_port = 192.168.10.140
upload_flags =
    --auth=cnclaser
