[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:esp32dev_usb]
upload_speed = 921600
lib_deps =
    lovyan03/LovyanGFX@^1.2.7

[env:esp32dev_ota]
upload_protocol = espota
upload_port = 192.168.1.140
upload_flags =
    --auth=cnclaser
    --timeout=30
lib_deps =
    lovyan03/LovyanGFX@^1.2.7

[env:esp32c6_supermini_usb]
board = esp32-c6-devkitm-1
upload_port = /dev/ttyACM0
upload_speed = 921600
build_flags =
    -D BOARD_ESP32C6_SUPERMINI=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D STM32_UART_RX_GPIO=17
    -D STM32_UART_TX_GPIO=16

[env:esp32c6_supermini_ota]
board = esp32-c6-devkitm-1
upload_protocol = espota
upload_port = 192.168.1.140
upload_flags =
    --auth=cnclaser
    --timeout=30
build_flags =
    -D BOARD_ESP32C6_SUPERMINI=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D STM32_UART_RX_GPIO=17
    -D STM32_UART_TX_GPIO=16
